version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.2.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0 # required if not using the demo security configuration
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./root-ca.pem:/usr/share/opensearch/config/root-CA.pem
      - ./node1.pem:/usr/share/opensearch/config/node.pem
      - ./node1-key.pem:/usr/share/opensearch/config/node-key.pem
      - ./admin.pem:/usr/share/opensearch/config/Admin.pem
      - ./admin-key.pem:/usr/share/opensearch/config/Admin-key.pem
      - ./custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml
#      - ./internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
#      - ./roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
#      - ./tenants.yml:/usr/share/opensearch/config/opensearch-security/tenants.yml
#      - ./roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
#      - ./action_groups.yml:/usr/share/opensearch/config/opensearch-security/action_groups.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:2.2.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
      - network.host=0.0.0.0
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./root-ca.pem:/usr/share/opensearch/config/root-CA.pem
      - ./node2.pem:/usr/share/opensearch/config/node.pem
      - ./node2-key.pem:/usr/share/opensearch/config/node-key.pem
      - ./admin.pem:/usr/share/opensearch/config/Admin.pem
      - ./admin-key.pem:/usr/share/opensearch/config/Admin-key.pem
      - ./custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml
#      - ./internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
#      - ./roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
#      - ./tenants.yml:/usr/share/opensearch/config/opensearch-security/tenants.yml
#      - ./roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
#      - ./action_groups.yml:/usr/share/opensearch/config/opensearch-security/action_groups.yml
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.2.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # must be a string with no spaces when specified as an environment variable
#    volumes:
#      - ./custom-opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
